[project]
name = "testhugging"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=12.0.0",
]

[tool.pyinstaller]
# PyInstaller configuration
exe = "main.py"
onefile = true
windowed = true

[tool.pyinstaller.options]
hiddenimports = ["customtkinter", "darkdetect"]
collectall = ["customtkinter"]
